// <auto-generated />
using System;
using Aplicacion.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aplicacion.Migrations
{
    [DbContext(typeof(DBPRUEBAContext))]
    [Migration("20240404160758_dev01")]
    partial class dev01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Aplicacion.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cedula");

                    b.Property<string>("Departamento")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("departamento");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Aplicacion.Models.Asistencium", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool?>("Estado")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdAlumno")
                        .HasColumnType("int")
                        .HasColumnName("id_alumno");

                    b.Property<int?>("IdCurso")
                        .HasColumnType("int")
                        .HasColumnName("id_curso");

                    b.HasKey("Id");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdCurso");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("Aplicacion.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaTermino")
                        .HasColumnType("date")
                        .HasColumnName("fecha_termino");

                    b.Property<string>("Horario")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("horario");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("TituloObtenido")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("titulo_obtenido");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Aplicacion.Models.HistoricoCursosAlumno", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("date")
                        .HasColumnName("fecha_registro");

                    b.Property<int?>("IdAlumno")
                        .HasColumnType("int")
                        .HasColumnName("id_alumno");

                    b.Property<int?>("IdCurso")
                        .HasColumnType("int")
                        .HasColumnName("id_curso");

                    b.HasKey("Id");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdCurso");

                    b.ToTable("Historico_Cursos_Alumnos", (string)null);
                });

            modelBuilder.Entity("Aplicacion.Models.Tabla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Correo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tabla", (string)null);
                });

            modelBuilder.Entity("Aplicacion.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Clave")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("Confirmado")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Restablecer")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__USUARIO__5B65BF97A4D0431C");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("Aplicacion.Models.Asistencium", b =>
                {
                    b.HasOne("Aplicacion.Models.Alumno", "IdAlumnoNavigation")
                        .WithMany("Asistencia")
                        .HasForeignKey("IdAlumno")
                        .HasConstraintName("FK__Asistenci__id_al__5165187F");

                    b.HasOne("Aplicacion.Models.Curso", "IdCursoNavigation")
                        .WithMany("Asistencia")
                        .HasForeignKey("IdCurso")
                        .HasConstraintName("FK__Asistenci__id_cu__52593CB8");

                    b.Navigation("IdAlumnoNavigation");

                    b.Navigation("IdCursoNavigation");
                });

            modelBuilder.Entity("Aplicacion.Models.HistoricoCursosAlumno", b =>
                {
                    b.HasOne("Aplicacion.Models.Alumno", "IdAlumnoNavigation")
                        .WithMany("HistoricoCursosAlumnos")
                        .HasForeignKey("IdAlumno")
                        .HasConstraintName("FK__Historico__id_al__5535A963");

                    b.HasOne("Aplicacion.Models.Curso", "IdCursoNavigation")
                        .WithMany("HistoricoCursosAlumnos")
                        .HasForeignKey("IdCurso")
                        .HasConstraintName("FK__Historico__id_cu__5629CD9C");

                    b.Navigation("IdAlumnoNavigation");

                    b.Navigation("IdCursoNavigation");
                });

            modelBuilder.Entity("Aplicacion.Models.Alumno", b =>
                {
                    b.Navigation("Asistencia");

                    b.Navigation("HistoricoCursosAlumnos");
                });

            modelBuilder.Entity("Aplicacion.Models.Curso", b =>
                {
                    b.Navigation("Asistencia");

                    b.Navigation("HistoricoCursosAlumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
